### ISSUE TITLE
Setup is not explained in readme

### ISSUE THREAD

**Issue by matzex** [bernd289/testpage#3]
The proper setup of testpage on Apache2 can be a little bit tricky when not all configurations are known.

Proposed additions in Readme:
Activate SSI in Apache: https://httpd.apache.org/docs/current/mod/mod_include.html
Activate Hostname Lookup in Apache. Therefore change the following line from "Off" to "On" in the main apache2 conf, e.g. on Ubuntu 16.04/18.04
Original:
`HostnameLookups Off`
change to
`HostnameLookups On`

**Comment by bernd289** [comment]
Added. Thanks!
